routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'admin'], function () {
   Route::get('/', 'AdminController@index')->name('admin.index');
   Route::resource('/recipes', 'RecipeController');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('/register',[UserController::class, 'create'])->name('register.create');
    Route::post('/register',[UserController::class, 'store'])->name('register.store');
    Route::get('/login',[UserController::class, 'loginForm'])->name('login.create');
    Route::post('/login',[UserController::class, 'login'])->name('login');
});

Route::get('/logout',[UserController::class, 'logout'])->name('logout')->middleware('auth');

Route::group(['middleware' => ['localize', 'ShareCommonData']], function () {
    Route::group(['prefix' => '{locale}'], function () {
        Route::get('/', [PostController::class, 'index'])->name('post.index');
        Route::get('/post/{slug}', [PostController::class, 'show'])->name('post.show');
    });
});

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use HasFactory, HasSlug;

    protected $fillable = [
        'title',
        'description',
        'image',
        'user_id'
    ];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->doNotGenerateSlugsOnUpdate();
    }


    public function steps()
    {
        return $this->hasMany(Step::class);
    }

    public function ingredients()
    {
        return $this->hasMany(Ingredient::class);
    }


    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getImage()
    {
        if (!$this->image) {
            return asset('no-image.png');
        }

        return asset("storage/{$this->image}");
    }
}

app/Http/Controllers/Admin/RecipeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RecipeRequest;
use App\Services\Recipe\RecipeServiceInterface;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;

class RecipeController extends Controller
{

    private RecipeServiceInterface $recipeService;

    public function __construct(RecipeServiceInterface $recipeService)
    {
        $this->recipeService = $recipeService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $recipes = $this->recipeService->getPaginatedRecipes();

        return view('admin.recipe.index', compact('recipes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('admin.recipe.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     *
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $recipe = $this->recipeService->getRecipeById($id);

        return view('admin.recipe.edit', compact('recipe'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RecipeRequest $request
     *
     * @return RedirectResponse
     */
    public function store(RecipeRequest $request)
    {
        $this->recipeService->createRecipe($request);

        return redirect()
            ->route('recipes.index')
            ->with('success', 'Recipe added successfully');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RecipeRequest $request
     * @param int $id
     *
     * @return RedirectResponse
     */
    public function update(RecipeRequest $request, int $id): RedirectResponse
    {
        $this->recipeService->updateRecipe($request, $id);

        return redirect()
            ->route('recipes.index')
            ->with('success', 'Recipe updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        $recipe = $this->recipeService->deleteRecipe($id);

        return redirect()
            ->route('recipes.index')
            ->with('success', "Recipe {$recipe->name} deleted successfully.");
    }
}

resources/views/admin/recipe/create.blade.php
@extends('admin.layouts.layout')
@section('admin.layouts.content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>New Recipe</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">New Recipe</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <div class="card card-primary">
            <!-- form start -->
            <form action="{{ route('recipes.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title <sup style="color: red;">*</sup></label>
                        <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" placeholder="Enter Recipe Title">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Description <sup style="color: red;">*</sup></label>
                        <textarea name="description" class="form-control @error('name') is-invalid @enderror" rows="3" placeholder="Enter Recipe Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="file" id="image">
                                <label class="custom-file-label" for="image">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text">Upload</span>
                            </div>
                        </div>
                    </div>
                    <div class="ingredients">
                        <h3>Ingredients</h3>
                    </div>
                    <a class="btn btn-primary mb-3" id="add-ingredient" href="#">Add Ingredient</a>

                    <!-- TODO Will be implements on the next release -->
                    <div class="steps" style="display: none">
                        <h3>Steps</h3>
                    </div>
                    <a style="display: none" class="btn btn-primary mb-3" id="add-step" href="#">Add step</a>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <!-- /.content -->
@endsection

resources/views/admin/recipe/edit.blade.php
@extends('admin.layouts.layout')
@section('admin.layouts.content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Recipe</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Recipe "{{ $recipe->id }}"</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('recipes.update', ['recipe' => $recipe->id]) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Title</label>
                    <input type="text" name="title" value="{{ $recipe->title }}" class="form-control @error('name') is-invalid @enderror" placeholder="Enter Recipe Name">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Description</label>
                    <textarea name="description" class="form-control @error('name') is-invalid @enderror" rows="3" placeholder="Enter Recipe Description">{{ $recipe->description }}</textarea>
                </div>
                <div class="form-group">
                    @if ($recipe->image)
                        <div class="recipe-image">
                            <img class="recipe-image" width="150" src="{{ asset('storage/' . $recipe->image) }}" alt="Image for {{ $recipe->title }}">
                            <a href="#" onclick="confirmDeletingImage();">
                                <span class="badge badge-danger delete-badge">X</span>
                            </a>
                        </div>
                        <div class="hiddenImageFile d-none">
                            <label for="image">File input</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="image" value="{{ $recipe->image }}" id="image">
                                    <label class="custom-file-label" for="image">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                        </div>
                    @else
                        <label for="image">File input</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="image" value="{{ $recipe->image }}" id="image">
                                <label class="custom-file-label" for="image">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text">Upload</span>
                            </div>
                        </div>
                    @endif
                </div>
                <div class="ingredients">
                    <h3>Ingredients</h3>
                    @if ($recipe->ingredients)
                        @foreach($recipe->ingredients as $ingredient)
                            <div class="ingredient mb-3">
                                <div class="row">
                                    <input type="hidden" name="ingredients[{{ $ingredient->id }}][id]" value="{{ $ingredient->id }}">
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label>Name <sup style="color: red;">*</sup></label>
                                            <input data-id="{{ $ingredient->id }}" data-name="title" value="{{ $ingredient->title }}" type="text" name="ingredients[{{ $ingredient->id }}][title]" class="form-control" placeholder="Enter Ingredient Title">
                                        </div>
                                    </div>
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label>Description <sup style="color: red;">*</sup></label>
                                            <input data-id="{{ $ingredient->id }}" value="{{ $ingredient->description }}" data-name="description" type="text" name="ingredients[{{ $ingredient->id }}][description]" class="form-control" placeholder="Enter Ingredient Description">
                                        </div>
                                    </div>
                                    <div class="col-sm-2 d-flex align-items-center justify-content-center">
                                        <div class="form-group">
                                            <button type="button" class="delete-row" onclick="deleteRow($(this))">
                                                <i class="fas fa-minus-circle"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @endif
                </div>
                <a class="btn btn-primary mb-3" id="add-ingredient" href="#">Add Ingredient</a>

                <!-- TODO Will be implements on the next release -->
                <div class="steps" style="display: none">
                    <h3>Steps</h3>
                    @if ($recipe->steps)
                        @foreach($recipe->steps as $step)
                            <div class="step mb-3">
                                <div class="row">
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <label for="image-0">Image</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" name="steps[0][image]" id="image-0">
                                                    <label class="custom-file-label" for="image-0">Choose file</label>
                                                </div>
                                                <div class="input-group-append">
                                                    <span class="input-group-text">Upload</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Title <sup style="color: red;">*</sup></label>
                                            <input data-id="{{ $step->id }}" data-name="title" type="text" value="{{ $step->title }}" name="steps[{{ $step->id }}][title]" class="form-control" placeholder="Enter Step Title">
                                        </div>
                                    </div>
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <label>Description <sup style="color: red;">*</sup></label>
                                            <textarea data-id="{{ $step->id }}" rows="3" data-name="description" name="steps[{{ $step->id }}][description]" class="form-control" placeholder="Enter Step Description">{{ $step->description }}</textarea>
                                        </div>
                                    </div>
                                    <div class="col-sm-2 d-flex align-items-center justify-content-center">
                                        <div class="form-group">
                                            <button type="button" class="delete-row" onclick="deleteRow($(this))">
                                                <i class="fas fa-minus-circle"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @endif
                </div>
                <a style="display: none" class="btn btn-primary mb-3" id="add-step" href="#">Add step</a>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <!-- /.content -->
@endsection

resources/views/admin/recipe/index.blade.php
@extends('admin.layouts.layout')
@section('admin.layouts.content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Recipes</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                            <li class="breadcrumb-item active">Recipes</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Title</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary mb-3" href="{{ route('recipes.create') }}">Add new Recipe</a>
                    @if (count($recipes))
                        <div class="mt-1">
                            <table class="table table-bordered text-nowrap table-hover">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th style="width: 150px;">Image</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Author</th>
                                        <th style="width: 30px">Actions</th>
                                    </tr>
                                </thead>
                            <tbody>
                            @foreach($recipes as $recipe)
                                <tr>
                                    <td>{{ $recipe->id }}</td>
                                    <td>
                                        <a href="{{ route('recipes.edit', ['recipe' => $recipe->id]) }}">
                                            @if ($recipe->image)
                                                <img width="150" src="{{ asset('storage/' . $recipe->image) }}" alt="Image for {{ $recipe->title }}">
                                            @else
                                                <img width="150" src="/assets/admin/img/default-150x150.png" alt="Image for {{ $recipe->title }}">
                                            @endif
                                        </a>
                                    </td>
                                    <td><a href="{{ route('recipes.edit', ['recipe' => $recipe->id]) }}">{{ $recipe->title }}</a></td>
                                    <td><p>{{ \Illuminate\Support\Str::limit($recipe->description, 50, $end='...') }}</p></td>
                                    <td><p>{{ $recipe->user->name }}</p></td>
                                    <td>
                                        <form action="{{ route('recipes.destroy', ['recipe' => $recipe->id]) }}" method="post" class="text-center">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete this recipe?');">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-1 clearfix">
                        {{ $recipes->links() }}
                    </div>
                    @else
                        <p class="text-center">No Recipes</p>
                    @endif
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    &copy Foodstarr 2021 All rights reserved
                </div>
                <!-- /.card-footer-->
            </div>
            <!-- /.card -->

        </section>
        <!-- /.content -->
@endsection